---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
  namespace: minio-system
  labels:
    app.kubernetes.io/name: minio-operator
    app.kubernetes.io/version: "v5.0.9"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minio-operator
      app.kubernetes.io/instance: minio-console
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio-operator
        app.kubernetes.io/instance: minio-console
    spec:
      serviceAccountName: console-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: operator
          image: "quay.io/minio/operator:v5.0.9"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
              name: http
            - containerPort: 9443
              name: https
          args:
            - ui
            - --certs-dir=/tmp/certs
          resources:
            requests:
              cpu: 0.25
              memory: 512Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-operator
  namespace: minio-system
  labels:
    app.kubernetes.io/name: minio-operator
    app.kubernetes.io/version: "v5.0.9"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minio-operator
      app.kubernetes.io/instance: minio
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio-operator
        app.kubernetes.io/instance: minio
    spec:
      serviceAccountName: minio-operator
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - minio-operator
            topologyKey: kubernetes.io/hostname
      containers:
        - name: operator
          image: "quay.io/minio/operator:v5.0.9"
          imagePullPolicy: IfNotPresent
          args:
            - controller
          resources:
            requests:
              cpu: 200m
              ephemeral-storage: 500Mi
              memory: 256Mi
          securityContext:
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
