---
# Source: operator/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: redpanda-operator-config
  namespace: redpanda-system
  labels:
    app.kubernetes.io/name: redpanda-operator
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/version: "v23.2.12"
data:
  controller_manager_config.yaml: |
    map[apiVersion:controller-runtime.sigs.k8s.io/v1alpha1 health:map[healthProbeBindAddress::8081] kind:ControllerManagerConfig leaderElection:map[leaderElect:true resourceName:aa9fc693.vectorized.io] metrics:map[bindAddress:127.0.0.1:8080] webhook:map[port:9443]]
