---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda-operator
  namespace: redpanda-system
  labels:
    app.kubernetes.io/name: redpanda-operator
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/version: "v23.2.12"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redpanda-operator
      app.kubernetes.io/instance: redpanda
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redpanda-operator
        app.kubernetes.io/instance: redpanda
      annotations:
    spec:
      serviceAccountName: redpanda-operator
      containers:
      - name: manager
        image: "docker.redpanda.com/redpandadata/redpanda-operator:v23.2.12"
        imagePullPolicy: IfNotPresent
        args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        - --configurator-tag=v23.2.12
        - --configurator-base-image=docker.redpanda.com/redpandadata/configurator
        - --webhook-enabled=false
        command:
        - /manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz/
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
        # volumeMounts:
        # - mountPath: /tmp/k8s-webhook-server/serving-certs
        #   name: cert
        #   readOnly: true
        resources:
            {}
      - name: kube-rbac-proxy
        args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
        ports:
        - containerPort: 8443
          name: https
      securityContext:
        runAsUser: 65532
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: redpanda-webhook-cert
