---
# Source: operator/templates/service_account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redpanda-operator
  namespace: redpanda-system
  labels:
    app.kubernetes.io/name: redpanda-operator
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/version: "v23.2.12"
---
# Source: operator/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redpanda-operator
  labels:
    app.kubernetes.io/name: redpanda-operator
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/version: "v23.2.12"
rules:
- apiGroups:
    - ""
  resources:
    - persistentvolumes
  verbs:
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - apps
  resources:
    - deployments
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - apps
  resources:
    - statefulsets
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - cert-manager.io
  resources:
    - certificates
    - issuers
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - cert-manager.io
  resources:
    - clusterissuers
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - configmaps
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - create
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - nodes
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - ""
  resources:
    - persistentvolumeclaims
  verbs:
    - delete
    - get
    - list
    - watch
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - delete
    - get
    - list
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - pods/finalizers
  verbs:
    - update
- apiGroups:
    - ""
  resources:
    - pods/status
  verbs:
    - patch
    - update
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - create
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - serviceaccounts
  verbs:
    - create
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - services
  verbs:
    - create
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - networking.k8s.io
  resources:
    - ingresses
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - policy
  resources:
    - poddisruptionbudgets
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - clusterrolebindings
    - clusterroles
  verbs:
    - create
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - redpanda.vectorized.io
  resources:
    - clusters
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - redpanda.vectorized.io
  resources:
    - clusters/finalizers
  verbs:
    - update
- apiGroups:
    - redpanda.vectorized.io
  resources:
    - clusters/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - redpanda.vectorized.io
  resources:
    - consoles
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - redpanda.vectorized.io
  resources:
    - consoles/finalizers
  verbs:
    - update
- apiGroups:
    - redpanda.vectorized.io
  resources:
    - consoles/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - cluster.redpanda.com
  resources:
    - topics
  verbs:
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - cluster.redpanda.com
  resources:
    - topics/finalizers
  verbs:
    - update
- apiGroups:
    - cluster.redpanda.com
  resources:
    - topics/status
  verbs:
    - get
    - patch
    - update
---
# Source: operator/templates/clusterrole_metrics.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redpanda-operator-metrics-reader
  labels:
    app.kubernetes.io/name: redpanda-operator
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/version: "v23.2.12"
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
# Source: operator/templates/clusterrole_proxy.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redpanda-operator-proxy-role
  labels:
    app.kubernetes.io/name: redpanda-operator
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/version: "v23.2.12"
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
# Source: operator/templates/clusterrole_binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: redpanda-operator
  labels:
    app.kubernetes.io/name: redpanda-operator
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/version: "v23.2.12"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: redpanda-operator
subjects:
- kind: ServiceAccount
  name: redpanda-operator
  namespace: redpanda-system
---
# Source: operator/templates/clusterrole_proxy_binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: redpanda-operator-proxy-role
  labels:
    app.kubernetes.io/name: redpanda-operator
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/version: "v23.2.12"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: redpanda-operator-proxy-role
subjects:
- kind: ServiceAccount
  name: redpanda-operator
  namespace: redpanda-system
---
# Source: operator/templates/extra_role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: redpanda-operator-pvc
  namespace: redpanda-system
  labels:
    app.kubernetes.io/name: redpanda-operator
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/version: "v23.2.12"
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - list
  - delete
---
# Source: operator/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: redpanda-operator-election-role
  namespace: redpanda-system
  labels:
    app.kubernetes.io/name: redpanda-operator
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/version: "v23.2.12"
rules:
- apiGroups:
  - ""
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
# Source: operator/templates/extra_role.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: redpanda-operator-pvc
  namespace: redpanda-system
  labels:
    app.kubernetes.io/name: redpanda-operator
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/version: "v23.2.12"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: redpanda-operator-pvc
subjects:
  - kind: ServiceAccount
    name: redpanda-operator
    namespace: redpanda-system
---
# Source: operator/templates/role_binding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: redpanda-operator-election-rolebinding
  namespace: redpanda-system
  labels:
    app.kubernetes.io/name: redpanda-operator
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/version: "v23.2.12"
subjects:
- kind: ServiceAccount
  name: redpanda-operator
  namespace: redpanda-system
roleRef:
  kind: Role
  name: redpanda-operator-election-role
  apiGroup: rbac.authorization.k8s.io
