---
apiVersion: v1
kind: Service
metadata:
  name: redpanda-operator-metrics-service
  namespace: redpanda-system
  labels:
    app.kubernetes.io/name: redpanda-operator
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/version: "v23.2.12"
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app.kubernetes.io/name: redpanda-operator
    app.kubernetes.io/instance: redpanda
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda-operator-webhook-service
  namespace: redpanda-system
  labels:
    app.kubernetes.io/name: redpanda-operator
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/version: "v23.2.12"
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    app.kubernetes.io/name: redpanda-operator
    app.kubernetes.io/instance: redpanda
