###
### Permissions needed for the SparkApplication jobs
###
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  labels:
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/version: "v1beta2-1.3.8-3.1.1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-role
  namespace: spark-system
  labels:
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/version: "v1beta2-1.3.8-3.1.1"
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark
  labels:
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/version: "v1beta2-1.3.8-3.1.1"
subjects:
- kind: ServiceAccount
  name: spark
  namespace: default
roleRef:
  kind: ClusterRole
  name: spark-role
  apiGroup: rbac.authorization.k8s.io

###
### Permissions used by the operator
###
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-operator
  namespace: spark-system
  labels:
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/version: "v1beta2-1.3.8-3.1.1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-operator
  labels:
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/version: "v1beta2-1.3.8-3.1.1"
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - services
  - configmaps
  - secrets
  verbs:
  - create
  - get
  - delete
  - update
- apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - get
  - delete
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - resourcequotas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - get
  - update
  - delete
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - create
  - get
  - update
  - delete
- apiGroups:
  - sparkoperator.k8s.io
  resources:
  - sparkapplications
  - sparkapplications/status
  - scheduledsparkapplications
  - scheduledsparkapplications/status
  verbs:
  - "*"
  
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-operator
  labels:
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/version: "v1beta2-1.3.8-3.1.1"
subjects:
  - kind: ServiceAccount
    name: spark-operator
    namespace: spark-system
roleRef:
  kind: ClusterRole
  name: spark-operator
  apiGroup: rbac.authorization.k8s.io
